version: '3'
services:
  postgres:
    image: postgres
    container_name: db-postgres
    ports:
      - 6969:5432
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data/pgdata
        volume:
          nocopy: true

  gol-server:
    build: .
    ports:
      - 8080:8080
volumes:
  db-data:
    driver: local
